version: '2.3'

services:
  static:
    image: halverneus/static-file-server
    environment:
      - CORS=true
    ports:
      - 3080:8080
    volumes:
      - /Users/jbadaczewski/Source/bada/past/static:/web
    restart: always
